"""
Distinct powers
How many distinct terms are in the sequence generated by a^b
for 2 <= a <= 100 and 2 <= b <= 100?
"""

def power_combinations(a, b):
    result = []
    for i in range(2, a+1):
        for j in range(2, b+1):
            result.append(i ** j)
    return len(set(result))

if __name__ == '__main__':
    assert power_combinations(5, 5) == 15
    print(power_combinations(100, 100)) # 9183



